#
# Floor Heating Actuator Controller
# ESPHome PACKAGE configuration file
# See https://esphome.io/components/packages/
#

# Package available substitutions
substitutions:
  relay1_name: "Relay1"
  relay2_name: "Relay2"
  relay3_name: "Relay3"
  relay4_name: "Relay4"
  relay5_name: "Relay5"
  relay6_name: "Relay6"
  relay7_name: "Relay7"
  relay8_name: "Relay8"
  encryption_key: "your_encryption_key_here"
  ota_password: "your_ota_password_here"
  wifi_ssid: "your_wifi_ssid_here"
  wifi_password: "your_wifi_password_here"
  wifi_ap_password: "your_wifi_ap_password_here"

# You might want to override this:
esphome:
  name: floorheatingactuatorcontroller
  friendly_name: FloorHeatingActuatorController

# Board
esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ${encryption_key}


# Wireless Connectivity:
ota:
  - platform: esphome
    password: ${ota_password}
wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Floorheatingactuatorcontroller"
    password: ${wifi_ap_password}

  # attempt to resolve an issue where the ESP32 sometimes fails to reconnect to WiFi
  # and needs a power-cycle to recover
  reboot_timeout: 1min
  power_save_mode: none
  enable_btm: true  # 802.11v BSS Transition Management
  enable_rrm: true  # 802.11k Radio Resource Management


# Extra sensors:
text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP
      icon: mdi:ip-network-outline
    mac_address:
      name: MAC
      icon: mdi:network-outline
  - platform: version
    name: "ESPHome Version"

# Captive Portal is the portal created by this node when Wifi connection fails
captive_portal:
    
# Webserver is exposed under regular use
web_server:
  port: 80
  # Disable OTA updates for web_server only
  # Captive portal will still have OTA access since it auto-loads the web server OTA platform
  ota: false

# SPI bus configuration
# MOSI is not required because the slave device does not accept any input
#  SPI	MOSI    MISO    SCLK    CS
# VSPI	GPIO23	GPIO19	GPIO18	GPIO5
# HSPI	GPIO13	GPIO12	GPIO14	GPIO15
spi:
  miso_pin: GPIO16
  clk_pin: GPIO17

# Temperature sensors
sensor:
  # Temperature sensor on SPI, see https://esphome.io/components/sensor/max6675/
  - platform: max6675
    id: heating_pipe_sensor
    name: "Heating pipe Temperature"
    cs_pin: GPIO15
    update_interval: 60s

  # WiFi information sensors
  - platform: wifi_signal
    name: Signal Strength
    update_interval: 60s

  - platform: dht
    id: ambient_sensor
    pin: GPIO5
    model: DHT11
    temperature:
      name: "Ambient Temperature"
    humidity:
      name: "Ambient Humidity"
    update_interval: 60s

# Main relays controlling the floor heating zones
switch:
  # relays use GPIOS 12-14, 23,25-27, 32-33
  - platform: gpio
    name: "LED"
    pin: GPIO23
  - platform: gpio
    name: ${relay1_name}
    pin: GPIO13
  - platform: gpio
    name: ${relay2_name}
    pin: GPIO12
  - platform: gpio
    name: ${relay3_name}
    pin: GPIO14
  - platform: gpio
    name: ${relay4_name}
    pin: GPIO27
  - platform: gpio
    name: ${relay5_name}
    pin: GPIO26
  - platform: gpio
    name: ${relay6_name}
    pin: GPIO25
  - platform: gpio
    name: ${relay7_name}
    pin: GPIO33
  - platform: gpio
    name: ${relay8_name}
    pin: GPIO32
