name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # see https://github.com/esphome/esphome-project-template/tree/main/.github/workflows
  build:
    name: Build ESPHome project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
      - name: ESPHome
        uses: esphome/build-action@v7
        with:
          yaml-file: example-instance.yaml
          version: stable
